### ISSUE TITLE
Reproducing glasses dataset

### ISSUE THREAD

**Issue by sbrugman** [chenhsuanlin/spatial-transformer-GAN#17]
There are two issues regarding the `glasses` dataset:
- Firstly, the pretrained model archive contains the files:
```
models_0/test_warp4_it40000_D.ckpt.data-00000-of-00001
models_0/test_warp4_it40000_D.ckpt.index
models_0/test_warp4_it40000_D.ckpt.meta
models_0/test_warp4_it40000_GP.ckpt.data-00000-of-00001
models_0/test_warp4_it40000_GP.ckpt.index
models_0/test_warp4_it40000_GP.ckpt.meta
```

While the `test.sh` file calls another file:

```
python3 eval_STGAN.py --loadGP=0/test_warp5_it50000 --warpN=5 --loadImage=dataset/example_test.png
```

Presumably this should be changed to, assuming the files in the archive are valid:

```
python3 eval_STGAN.py --loadGP=0/test_warp4_it40000 --warpN=4 --loadImage=dataset/example_test.png
``` 

- Secondly, when using the pretrained model, we obtain the following errorneous output:

```
=======================================================
eval_STGAN.py (ST-GAN with homography)
=======================================================
(0) test
------------------------------------------
batch size: 10, warps: 4
image size: 144x144
------------------------------------------
building graph...
loading test data...
======= EVALUATION START =======
2019-01-10 10:57:56.856604: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2019-01-10 10:57:56.857046: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:04.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2019-01-10 10:57:56.857084: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-01-10 10:57:57.186289: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-01-10 10:57:57.186356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-01-10 10:57:57.186375: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-01-10 10:57:57.186665: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10758 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [12975,256] rhs shape= [10380,256]
	 [[{{node save/Assign_53}} = Assign[T=DT_FLOAT, _class=["loc:@geometric/warp3/fc6/weight"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](geometric/warp3/fc6/weight, save/RestoreV2/_107)]]
	 [[{{node save/RestoreV2/_98}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_103_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:49)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1546, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [12975,256] rhs shape= [10380,256]
	 [[node save/Assign_53 (defined at eval_STGAN.py:44)  = Assign[T=DT_FLOAT, _class=["loc:@geometric/warp3/fc6/weight"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](geometric/warp3/fc6/weight, save/RestoreV2/_107)]]
	 [[{{node save/RestoreV2/_98}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_103_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:49)]]

Caused by op 'save/Assign_53', defined at:
  File "eval_STGAN.py", line 44, in <module>
    saver_GP = tf.train.Saver(var_list=varsGP)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [12975,256] rhs shape= [10380,256]
	 [[node save/Assign_53 (defined at eval_STGAN.py:44)  = Assign[T=DT_FLOAT, _class=["loc:@geometric/warp3/fc6/weight"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](geometric/warp3/fc6/weight, save/RestoreV2/_107)]]
	 [[{{node save/RestoreV2/_98}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_103_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:49)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval_STGAN.py", line 53, in <module>
    util.restoreModel(opt,sess,saver_GP,opt.loadGP,"GP")
  File "/content/spatial-transformer-GAN/glasses/util.py", line 38, in restoreModel
    saver.restore(sess,"models_{0}_{1}.ckpt".format(path,net))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1582, in restore
    err, "a mismatch between the current graph and the graph")
tensorflow.python.framework.errors_impl.InvalidArgumentError: Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [12975,256] rhs shape= [10380,256]
	 [[node save/Assign_53 (defined at eval_STGAN.py:44)  = Assign[T=DT_FLOAT, _class=["loc:@geometric/warp3/fc6/weight"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](geometric/warp3/fc6/weight, save/RestoreV2/_107)]]
	 [[{{node save/RestoreV2/_98}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_103_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:49)]]

Caused by op 'save/Assign_53', defined at:
  File "eval_STGAN.py", line 44, in <module>
    saver_GP = tf.train.Saver(var_list=varsGP)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 428, in _AddRestoreOps
    assign_ops.append(saveable.restore(saveable_tensors, shapes))
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 119, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/state_ops.py", line 221, in assign
    validate_shape=validate_shape)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 61, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Assign requires shapes of both tensors to match. lhs shape= [12975,256] rhs shape= [10380,256]
	 [[node save/Assign_53 (defined at eval_STGAN.py:44)  = Assign[T=DT_FLOAT, _class=["loc:@geometric/warp3/fc6/weight"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](geometric/warp3/fc6/weight, save/RestoreV2/_107)]]
	 [[{{node save/RestoreV2/_98}} = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_103_save/RestoreV2", _device="/job:localhost/replica:0/task:0/device:CPU:0"](save/RestoreV2:49)]]
```

**Comment by sbrugman** [comment]
The error was due to confusion over the pretrained model links, I had to use https://cmu.box.com/shared/static/5ad2lbjuvze9iey2up6hcisg6dctii4h.gz instead of https://cmu.box.com/shared/static/ygl08wfsc2omutwrvra3u7zjjsu1ovwv.gz.
